services:
  api:
    entrypoint: node
    volumes:
      - ./src:/app
    expose:
      - 3000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 1s
      timeout: 500ms
      retries: 3

  test_runner:
    image: grafana/k6
    command: run -e  /tests/load-test.js
    volumes:
      - ./tests:/tests
